apiVersion: witboost.com/v2
kind: ComponentType
metadata:
  name: workload
  displayName: Workload
  description: Operational task involved in creating, ingesting, managing, or utilizing data of data products within an organization
spec:
  resourceTypeId: workload
  partOfSystem: systemtype:default/dataproduct
  consumable: false
  shoppable: false
  readsFrom:
    - componenttype:default/outputport
